-- ============================================================
-- SMART SCHOOL MANAGEMENT SYSTEM - REFINED POSTGRESQL SCHEMA
-- Reference only. This file has NOT been applied to the app.
--
-- Design goals:
-- - Match the current smart_school_backend naming where practical.
-- - Keep integer role/user/school/student IDs compatible with current code.
-- - Add production-ready tenant structure, academic setup, fees,
--   attendance, reports, notifications, sync, and audit support.
-- - Use VARCHAR + CHECK constraints instead of PostgreSQL ENUMs so
--   future migrations remain easier.
--
-- Do not run this against the existing database directly. Convert it
-- into Alembic migrations module by module when implementation starts.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- Helper: updated_at trigger
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 1. RBAC
-- ============================================================

CREATE TABLE roles (
    id              INTEGER PRIMARY KEY,
    name            VARCHAR(50) NOT NULL UNIQUE,
    description     VARCHAR(255),
    is_system_role  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE permissions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(100) NOT NULL UNIQUE,
    description     VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE role_permissions (
    role_id         INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id   INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- ============================================================
-- 2. Platform / Tenants
-- ============================================================

CREATE TABLE schools (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(150) NOT NULL,
    school_code           VARCHAR(30) NOT NULL UNIQUE,
    address               TEXT,
    phone                 VARCHAR(50),
    email                 VARCHAR(255),
    logo_url              TEXT,
    country               VARCHAR(80) NOT NULL DEFAULT 'Uganda',
    currency_code         VARCHAR(3) NOT NULL DEFAULT 'UGX',
    timezone              VARCHAR(80) NOT NULL DEFAULT 'Africa/Kampala',
    subscription_status   VARCHAR(30) NOT NULL DEFAULT 'trial',
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_schools_subscription_status
        CHECK (subscription_status IN ('trial', 'active', 'expired', 'cancelled', 'suspended')),
    CONSTRAINT ck_schools_currency_code
        CHECK (currency_code = UPPER(currency_code) AND length(currency_code) = 3)
);

CREATE UNIQUE INDEX uq_schools_code_ci ON schools (lower(school_code));
CREATE INDEX ix_schools_active ON schools (is_active);

CREATE TABLE school_settings (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id               INTEGER NOT NULL UNIQUE REFERENCES schools(id) ON DELETE CASCADE,
    terms_per_year          INTEGER NOT NULL DEFAULT 3,
    grading_system          VARCHAR(50) NOT NULL DEFAULT 'UNEB',
    sms_notifications       BOOLEAN NOT NULL DEFAULT TRUE,
    email_notifications     BOOLEAN NOT NULL DEFAULT TRUE,
    allow_partial_payment   BOOLEAN NOT NULL DEFAULT TRUE,
    low_bandwidth_mode      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_school_settings_terms
        CHECK (terms_per_year BETWEEN 1 AND 4)
);

CREATE TABLE school_branding (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id         INTEGER NOT NULL UNIQUE REFERENCES schools(id) ON DELETE CASCADE,
    primary_color     VARCHAR(20),
    secondary_color   VARCHAR(20),
    banner_url        TEXT,
    motto             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE subscription_plans (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    price           NUMERIC(12, 2) NOT NULL,
    currency_code   VARCHAR(3) NOT NULL DEFAULT 'UGX',
    max_students    INTEGER,
    max_teachers    INTEGER,
    features        JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_subscription_plans_price
        CHECK (price >= 0),
    CONSTRAINT ck_subscription_plans_currency
        CHECK (currency_code = UPPER(currency_code) AND length(currency_code) = 3),
    CONSTRAINT ck_subscription_plans_limits
        CHECK (
            (max_students IS NULL OR max_students > 0)
            AND (max_teachers IS NULL OR max_teachers > 0)
        )
);

CREATE TABLE school_subscriptions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    plan_id         INTEGER NOT NULL REFERENCES subscription_plans(id),
    status          VARCHAR(30) NOT NULL DEFAULT 'trial',
    starts_at       DATE NOT NULL,
    expires_at      DATE NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_school_subscriptions_status
        CHECK (status IN ('trial', 'active', 'expired', 'cancelled', 'suspended')),
    CONSTRAINT ck_school_subscriptions_dates
        CHECK (expires_at >= starts_at)
);

CREATE INDEX ix_school_subscriptions_school ON school_subscriptions (school_id);
CREATE INDEX ix_school_subscriptions_status ON school_subscriptions (status);

-- ============================================================
-- 3. Users and Authentication
-- ============================================================

CREATE TABLE users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role_id         INTEGER NOT NULL REFERENCES roles(id),
    school_id       INTEGER REFERENCES schools(id),
    phone           VARCHAR(50),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_users_school_scope_by_role
        CHECK (
            (role_id = 1 AND school_id IS NULL)
            OR
            (role_id <> 1 AND school_id IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));
CREATE INDEX ix_users_school_id ON users (school_id);
CREATE INDEX ix_users_role_id ON users (role_id);
CREATE INDEX ix_users_active ON users (is_active);
CREATE UNIQUE INDEX uq_users_school_id_pair ON users (school_id, id);

CREATE TABLE refresh_tokens (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL UNIQUE,
    device_name     VARCHAR(100),
    ip_address      VARCHAR(80),
    user_agent      TEXT,
    expires_at      TIMESTAMPTZ NOT NULL,
    revoked_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);

CREATE TABLE login_attempts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
    email           VARCHAR(255),
    ip_address      VARCHAR(80),
    success         BOOLEAN NOT NULL,
    failure_reason  VARCHAR(120),
    attempted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_login_attempts_user_id ON login_attempts (user_id);
CREATE INDEX ix_login_attempts_email ON login_attempts (lower(email));
CREATE INDEX ix_login_attempts_attempted_at ON login_attempts (attempted_at);

-- ============================================================
-- 4. People
-- ============================================================

CREATE TABLE students (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id),
    user_id             INTEGER UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    admission_number    VARCHAR(80),
    name                VARCHAR(150) NOT NULL,
    class_name          VARCHAR(80),
    stream_name         VARCHAR(80),
    date_of_birth       DATE,
    gender              VARCHAR(20),
    photo_url           TEXT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_students_school_admission
        UNIQUE (school_id, admission_number),
    CONSTRAINT ck_students_gender
        CHECK (gender IS NULL OR gender IN ('male', 'female', 'other')),
    CONSTRAINT ck_students_birth_date
        CHECK (date_of_birth IS NULL OR date_of_birth <= CURRENT_DATE)
);

CREATE INDEX ix_students_school_id ON students (school_id);
CREATE INDEX ix_students_admission_number ON students (admission_number);
CREATE INDEX ix_students_class_stream ON students (school_id, class_name, stream_name);
CREATE UNIQUE INDEX uq_students_school_id_pair ON students (school_id, id);

CREATE TABLE student_guardians (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    student_id      INTEGER NOT NULL,
    guardian_id     INTEGER NOT NULL,
    relationship    VARCHAR(50),
    is_primary      BOOLEAN NOT NULL DEFAULT FALSE,
    can_receive_sms BOOLEAN NOT NULL DEFAULT TRUE,
    can_make_payment BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_student_guardian
        UNIQUE (student_id, guardian_id),
    CONSTRAINT fk_student_guardians_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_student_guardians_guardian_school
        FOREIGN KEY (school_id, guardian_id)
        REFERENCES users(school_id, id)
        ON DELETE CASCADE
);

CREATE INDEX ix_student_guardians_student_id ON student_guardians (student_id);
CREATE INDEX ix_student_guardians_guardian_id ON student_guardians (guardian_id);
CREATE UNIQUE INDEX uq_student_guardians_primary
    ON student_guardians (student_id)
    WHERE is_primary IS TRUE;

CREATE TABLE staff_profiles (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    user_id         INTEGER NOT NULL,
    staff_number    VARCHAR(80),
    department      VARCHAR(100),
    date_joined     DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_staff_profiles_school_staff_number
        UNIQUE (school_id, staff_number),
    CONSTRAINT uq_staff_profiles_user
        UNIQUE (user_id),
    CONSTRAINT fk_staff_profiles_user_school
        FOREIGN KEY (school_id, user_id)
        REFERENCES users(school_id, id)
        ON DELETE CASCADE
);

CREATE TABLE teacher_profiles (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    user_id             INTEGER NOT NULL,
    employee_number     VARCHAR(80),
    qualification       TEXT,
    specialization      VARCHAR(100),
    date_employed       DATE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_teacher_profiles_school_employee
        UNIQUE (school_id, employee_number),
    CONSTRAINT uq_teacher_profiles_user
        UNIQUE (user_id),
    CONSTRAINT fk_teacher_profiles_user_school
        FOREIGN KEY (school_id, user_id)
        REFERENCES users(school_id, id)
        ON DELETE CASCADE
);

CREATE INDEX ix_teacher_profiles_school_id ON teacher_profiles (school_id);
CREATE UNIQUE INDEX uq_teacher_profiles_school_id_pair ON teacher_profiles (school_id, id);

CREATE TABLE parent_profiles (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    user_id         INTEGER NOT NULL,
    occupation      VARCHAR(100),
    address         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_parent_profiles_user
        UNIQUE (user_id),
    CONSTRAINT fk_parent_profiles_user_school
        FOREIGN KEY (school_id, user_id)
        REFERENCES users(school_id, id)
        ON DELETE CASCADE
);

-- ============================================================
-- 5. Academic Structure
-- ============================================================

CREATE TABLE academic_years (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(20) NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    is_current      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_academic_years_school_name
        UNIQUE (school_id, name),
    CONSTRAINT ck_academic_years_dates
        CHECK (end_date >= start_date)
);

CREATE INDEX ix_academic_years_school_id ON academic_years (school_id);
CREATE UNIQUE INDEX uq_academic_years_one_current
    ON academic_years (school_id)
    WHERE is_current IS TRUE;
CREATE UNIQUE INDEX uq_academic_years_school_id_pair ON academic_years (school_id, id);

CREATE TABLE terms (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    academic_year_id    INTEGER NOT NULL,
    name                VARCHAR(50) NOT NULL,
    start_date          DATE NOT NULL,
    end_date            DATE NOT NULL,
    is_current          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_terms_school_year_name
        UNIQUE (school_id, academic_year_id, name),
    CONSTRAINT fk_terms_academic_year_school
        FOREIGN KEY (school_id, academic_year_id)
        REFERENCES academic_years(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT ck_terms_dates
        CHECK (end_date >= start_date)
);

CREATE INDEX ix_terms_school_id ON terms (school_id);
CREATE UNIQUE INDEX uq_terms_one_current
    ON terms (school_id)
    WHERE is_current IS TRUE;
CREATE UNIQUE INDEX uq_terms_school_id_pair ON terms (school_id, id);

CREATE TABLE classes (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(80) NOT NULL,
    level           INTEGER,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_classes_school_name
        UNIQUE (school_id, name)
);

CREATE INDEX ix_classes_school_id ON classes (school_id);
CREATE UNIQUE INDEX uq_classes_school_id_pair ON classes (school_id, id);

CREATE TABLE streams (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    class_id        INTEGER NOT NULL,
    name            VARCHAR(80) NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_streams_school_class_name
        UNIQUE (school_id, class_id, name),
    CONSTRAINT fk_streams_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id)
        ON DELETE CASCADE
);

CREATE INDEX ix_streams_class_id ON streams (class_id);
CREATE UNIQUE INDEX uq_streams_school_id_pair ON streams (school_id, id);

CREATE TABLE subjects (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    code            VARCHAR(30),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_subjects_school_name
        UNIQUE (school_id, name),
    CONSTRAINT uq_subjects_school_code
        UNIQUE (school_id, code)
);

CREATE INDEX ix_subjects_school_id ON subjects (school_id);
CREATE UNIQUE INDEX uq_subjects_school_id_pair ON subjects (school_id, id);

CREATE TABLE class_subjects (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    class_id        INTEGER NOT NULL,
    subject_id      INTEGER NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_class_subjects_school_class_subject
        UNIQUE (school_id, class_id, subject_id),
    CONSTRAINT fk_class_subjects_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_class_subjects_subject_school
        FOREIGN KEY (school_id, subject_id)
        REFERENCES subjects(school_id, id)
        ON DELETE CASCADE
);

CREATE TABLE teacher_assignments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    teacher_profile_id  INTEGER NOT NULL,
    class_id            INTEGER NOT NULL,
    stream_id           INTEGER,
    subject_id          INTEGER NOT NULL,
    term_id             INTEGER NOT NULL,
    is_class_teacher    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_teacher_assignments_scope
        UNIQUE (school_id, teacher_profile_id, class_id, stream_id, subject_id, term_id),
    CONSTRAINT fk_teacher_assignments_teacher_school
        FOREIGN KEY (school_id, teacher_profile_id)
        REFERENCES teacher_profiles(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_teacher_assignments_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id),
    CONSTRAINT fk_teacher_assignments_stream_school
        FOREIGN KEY (school_id, stream_id)
        REFERENCES streams(school_id, id),
    CONSTRAINT fk_teacher_assignments_subject_school
        FOREIGN KEY (school_id, subject_id)
        REFERENCES subjects(school_id, id),
    CONSTRAINT fk_teacher_assignments_term_school
        FOREIGN KEY (school_id, term_id)
        REFERENCES terms(school_id, id)
);

CREATE INDEX ix_teacher_assignments_school_id ON teacher_assignments (school_id);

CREATE TABLE student_enrollments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    student_id          INTEGER NOT NULL,
    class_id            INTEGER NOT NULL,
    stream_id           INTEGER,
    academic_year_id    INTEGER NOT NULL,
    enrolled_at         DATE NOT NULL DEFAULT CURRENT_DATE,
    exited_at           DATE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_student_enrollments_school_student_year
        UNIQUE (school_id, student_id, academic_year_id),
    CONSTRAINT fk_student_enrollments_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_student_enrollments_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id),
    CONSTRAINT fk_student_enrollments_stream_school
        FOREIGN KEY (school_id, stream_id)
        REFERENCES streams(school_id, id),
    CONSTRAINT fk_student_enrollments_year_school
        FOREIGN KEY (school_id, academic_year_id)
        REFERENCES academic_years(school_id, id),
    CONSTRAINT ck_student_enrollments_dates
        CHECK (exited_at IS NULL OR exited_at >= enrolled_at)
);

CREATE INDEX ix_student_enrollments_student_id ON student_enrollments (student_id);
CREATE INDEX ix_student_enrollments_school_id ON student_enrollments (school_id);

-- ============================================================
-- 6. Fees and Payments
-- ============================================================

CREATE TABLE fee_categories (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(80) NOT NULL,
    description     TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fee_categories_school_name
        UNIQUE (school_id, name)
);

CREATE INDEX ix_fee_categories_school_id ON fee_categories (school_id);
CREATE UNIQUE INDEX uq_fee_categories_school_id_pair ON fee_categories (school_id, id);

CREATE TABLE fee_structures (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    fee_category_id     INTEGER NOT NULL,
    class_id            INTEGER,
    term_id             INTEGER,
    amount              NUMERIC(12, 2) NOT NULL,
    description         TEXT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_fee_structures_category_school
        FOREIGN KEY (school_id, fee_category_id)
        REFERENCES fee_categories(school_id, id),
    CONSTRAINT fk_fee_structures_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id),
    CONSTRAINT fk_fee_structures_term_school
        FOREIGN KEY (school_id, term_id)
        REFERENCES terms(school_id, id),
    CONSTRAINT ck_fee_structures_amount
        CHECK (amount >= 0)
);

CREATE INDEX ix_fee_structures_school_id ON fee_structures (school_id);

CREATE TABLE invoices (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          INTEGER NOT NULL,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    fee_category_id     INTEGER,
    academic_year       VARCHAR(20) NOT NULL,
    term                VARCHAR(20) NOT NULL,
    academic_year_id    INTEGER,
    term_id             INTEGER,
    amount              NUMERIC(12, 2) NOT NULL,
    description         TEXT,
    due_date            DATE NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'unpaid',
    created_by_id       INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_invoices_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id),
    CONSTRAINT fk_invoices_category_school
        FOREIGN KEY (school_id, fee_category_id)
        REFERENCES fee_categories(school_id, id),
    CONSTRAINT fk_invoices_academic_year_school
        FOREIGN KEY (school_id, academic_year_id)
        REFERENCES academic_years(school_id, id),
    CONSTRAINT fk_invoices_term_school
        FOREIGN KEY (school_id, term_id)
        REFERENCES terms(school_id, id),
    CONSTRAINT fk_invoices_created_by_school
        FOREIGN KEY (school_id, created_by_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_invoices_amount
        CHECK (amount >= 0),
    CONSTRAINT ck_invoices_status
        CHECK (status IN ('unpaid', 'partial', 'paid', 'overdue', 'cancelled', 'void'))
);

CREATE INDEX ix_invoices_school_id ON invoices (school_id);
CREATE INDEX ix_invoices_student_id ON invoices (student_id);
CREATE INDEX ix_invoices_status ON invoices (status);
CREATE INDEX ix_invoices_period ON invoices (school_id, academic_year, term);
CREATE UNIQUE INDEX uq_invoices_school_id_pair ON invoices (school_id, id);

CREATE TABLE invoice_items (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    invoice_id          INTEGER NOT NULL,
    fee_category_id     INTEGER,
    description         VARCHAR(255) NOT NULL,
    amount              NUMERIC(12, 2) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_invoice_items_invoice_school
        FOREIGN KEY (school_id, invoice_id)
        REFERENCES invoices(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_invoice_items_category_school
        FOREIGN KEY (school_id, fee_category_id)
        REFERENCES fee_categories(school_id, id),
    CONSTRAINT ck_invoice_items_amount
        CHECK (amount >= 0)
);

CREATE INDEX ix_invoice_items_invoice_id ON invoice_items (invoice_id);
CREATE UNIQUE INDEX uq_invoice_items_school_id_pair ON invoice_items (school_id, id);

CREATE TABLE payments (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      INTEGER NOT NULL,
    student_id      INTEGER NOT NULL,
    payer_id        INTEGER NOT NULL,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    amount          NUMERIC(12, 2) NOT NULL,
    method          VARCHAR(50) NOT NULL,
    reference       VARCHAR(120),
    status          VARCHAR(20) NOT NULL DEFAULT 'confirmed',
    paid_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_payments_invoice_school
        FOREIGN KEY (school_id, invoice_id)
        REFERENCES invoices(school_id, id),
    CONSTRAINT fk_payments_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id),
    CONSTRAINT fk_payments_payer_school
        FOREIGN KEY (school_id, payer_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_payments_amount
        CHECK (amount > 0),
    CONSTRAINT ck_payments_method
        CHECK (method IN ('cash', 'mobile_money', 'bank_transfer', 'cheque', 'card', 'other')),
    CONSTRAINT ck_payments_status
        CHECK (status IN ('pending', 'confirmed', 'failed', 'refunded', 'void'))
);

CREATE INDEX ix_payments_invoice_id ON payments (invoice_id);
CREATE INDEX ix_payments_student_id ON payments (student_id);
CREATE INDEX ix_payments_payer_id ON payments (payer_id);
CREATE INDEX ix_payments_school_id ON payments (school_id);
CREATE INDEX ix_payments_status ON payments (status);
CREATE UNIQUE INDEX uq_payments_reference_per_school
    ON payments (school_id, reference)
    WHERE reference IS NOT NULL;
CREATE UNIQUE INDEX uq_payments_school_id_pair ON payments (school_id, id);

CREATE TABLE payment_allocations (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    payment_id          INTEGER NOT NULL,
    invoice_item_id     INTEGER,
    amount              NUMERIC(12, 2) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_payment_allocations_payment_school
        FOREIGN KEY (school_id, payment_id)
        REFERENCES payments(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_payment_allocations_item_school
        FOREIGN KEY (school_id, invoice_item_id)
        REFERENCES invoice_items(school_id, id),
    CONSTRAINT ck_payment_allocations_amount
        CHECK (amount > 0)
);

CREATE TABLE receipts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    payment_id      INTEGER NOT NULL UNIQUE,
    receipt_number  VARCHAR(80) NOT NULL,
    issued_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pdf_url         TEXT,
    CONSTRAINT fk_receipts_payment_school
        FOREIGN KEY (school_id, payment_id)
        REFERENCES payments(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT uq_receipts_school_number
        UNIQUE (school_id, receipt_number)
);

CREATE INDEX ix_receipts_school_id ON receipts (school_id);
CREATE INDEX ix_receipts_payment_id ON receipts (payment_id);

CREATE TABLE discounts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    student_id      INTEGER NOT NULL,
    invoice_id      INTEGER,
    amount          NUMERIC(12, 2) NOT NULL,
    reason          TEXT,
    approved_by_id  INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_discounts_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id),
    CONSTRAINT fk_discounts_invoice_school
        FOREIGN KEY (school_id, invoice_id)
        REFERENCES invoices(school_id, id),
    CONSTRAINT fk_discounts_approved_by_school
        FOREIGN KEY (school_id, approved_by_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_discounts_amount
        CHECK (amount > 0)
);

CREATE TABLE refunds (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    payment_id          INTEGER NOT NULL,
    amount              NUMERIC(12, 2) NOT NULL,
    reason              TEXT,
    processed_by_id     INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_refunds_payment_school
        FOREIGN KEY (school_id, payment_id)
        REFERENCES payments(school_id, id),
    CONSTRAINT fk_refunds_processed_by_school
        FOREIGN KEY (school_id, processed_by_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_refunds_amount
        CHECK (amount > 0)
);

-- ============================================================
-- 7. Attendance
-- ============================================================

CREATE TABLE attendance_sessions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    class_id        INTEGER,
    stream_id       INTEGER,
    term_id         INTEGER,
    teacher_id      INTEGER,
    session_date    DATE NOT NULL,
    is_submitted    BOOLEAN NOT NULL DEFAULT FALSE,
    submitted_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_attendance_sessions_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id),
    CONSTRAINT fk_attendance_sessions_stream_school
        FOREIGN KEY (school_id, stream_id)
        REFERENCES streams(school_id, id),
    CONSTRAINT fk_attendance_sessions_term_school
        FOREIGN KEY (school_id, term_id)
        REFERENCES terms(school_id, id),
    CONSTRAINT fk_attendance_sessions_teacher_school
        FOREIGN KEY (school_id, teacher_id)
        REFERENCES users(school_id, id),
    CONSTRAINT uq_attendance_sessions_scope
        UNIQUE (school_id, class_id, stream_id, session_date)
);

CREATE INDEX ix_attendance_sessions_school_date ON attendance_sessions (school_id, session_date);
CREATE UNIQUE INDEX uq_attendance_sessions_school_id_pair ON attendance_sessions (school_id, id);

CREATE TABLE attendance (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          INTEGER NOT NULL,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    attendance_date     DATE NOT NULL,
    status              VARCHAR(20) NOT NULL,
    teacher_id          INTEGER,
    session_id          INTEGER,
    remarks             TEXT,
    edit_reason         TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_attendance_student_date
        UNIQUE (student_id, attendance_date),
    CONSTRAINT fk_attendance_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_attendance_teacher_school
        FOREIGN KEY (school_id, teacher_id)
        REFERENCES users(school_id, id),
    CONSTRAINT fk_attendance_session_school
        FOREIGN KEY (school_id, session_id)
        REFERENCES attendance_sessions(school_id, id),
    CONSTRAINT ck_attendance_status
        CHECK (status IN ('present', 'absent', 'late', 'excused'))
);

CREATE INDEX ix_attendance_school_id ON attendance (school_id);
CREATE INDEX ix_attendance_student_id ON attendance (student_id);
CREATE INDEX ix_attendance_date ON attendance (attendance_date);
CREATE INDEX ix_attendance_status ON attendance (status);
CREATE UNIQUE INDEX uq_attendance_school_id_pair ON attendance (school_id, id);

CREATE TABLE attendance_corrections (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    attendance_id   INTEGER NOT NULL,
    old_status      VARCHAR(20) NOT NULL,
    new_status      VARCHAR(20) NOT NULL,
    reason          TEXT,
    corrected_by_id INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_attendance_corrections_attendance_school
        FOREIGN KEY (school_id, attendance_id)
        REFERENCES attendance(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_attendance_corrections_user_school
        FOREIGN KEY (school_id, corrected_by_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_attendance_corrections_statuses
        CHECK (
            old_status IN ('present', 'absent', 'late', 'excused')
            AND new_status IN ('present', 'absent', 'late', 'excused')
        )
);

-- ============================================================
-- 8. Assessments and Report Cards
-- ============================================================

CREATE TABLE assessment_types (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    weight          NUMERIC(5, 2),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_assessment_types_school_name
        UNIQUE (school_id, name),
    CONSTRAINT ck_assessment_types_weight
        CHECK (weight IS NULL OR weight BETWEEN 0 AND 100)
);

CREATE UNIQUE INDEX uq_assessment_types_school_id_pair ON assessment_types (school_id, id);

CREATE TABLE assessments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    assessment_type_id  INTEGER NOT NULL,
    subject_id          INTEGER NOT NULL,
    class_id            INTEGER NOT NULL,
    term_id             INTEGER NOT NULL,
    total_marks         NUMERIC(6, 2) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_assessments_type_school
        FOREIGN KEY (school_id, assessment_type_id)
        REFERENCES assessment_types(school_id, id),
    CONSTRAINT fk_assessments_subject_school
        FOREIGN KEY (school_id, subject_id)
        REFERENCES subjects(school_id, id),
    CONSTRAINT fk_assessments_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id),
    CONSTRAINT fk_assessments_term_school
        FOREIGN KEY (school_id, term_id)
        REFERENCES terms(school_id, id),
    CONSTRAINT ck_assessments_total_marks
        CHECK (total_marks > 0)
);

CREATE INDEX ix_assessments_school_id ON assessments (school_id);
CREATE UNIQUE INDEX uq_assessments_school_id_pair ON assessments (school_id, id);

CREATE TABLE marks (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    assessment_id   INTEGER NOT NULL,
    student_id      INTEGER NOT NULL,
    score           NUMERIC(6, 2),
    remarks         TEXT,
    entered_by_id   INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_marks_assessment_student
        UNIQUE (assessment_id, student_id),
    CONSTRAINT fk_marks_assessment_school
        FOREIGN KEY (school_id, assessment_id)
        REFERENCES assessments(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_marks_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id),
    CONSTRAINT fk_marks_entered_by_school
        FOREIGN KEY (school_id, entered_by_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_marks_score
        CHECK (score IS NULL OR score >= 0)
);

CREATE INDEX ix_marks_school_id ON marks (school_id);
CREATE INDEX ix_marks_student_id ON marks (student_id);

CREATE TABLE grading_scales (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(50) NOT NULL,
    grade           VARCHAR(10) NOT NULL,
    min_score       NUMERIC(5, 2) NOT NULL,
    max_score       NUMERIC(5, 2) NOT NULL,
    points          INTEGER,
    remark          VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_grading_scales_school_name_grade
        UNIQUE (school_id, name, grade),
    CONSTRAINT ck_grading_scales_score_range
        CHECK (min_score >= 0 AND max_score >= min_score),
    CONSTRAINT ck_grading_scales_points
        CHECK (points IS NULL OR points >= 0)
);

CREATE TABLE report_card_summaries (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id               INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    student_id              INTEGER NOT NULL,
    academic_year           VARCHAR(20) NOT NULL,
    term                    VARCHAR(20) NOT NULL,
    academic_year_id        INTEGER,
    term_id                 INTEGER,
    class_id                INTEGER,
    total_marks             NUMERIC(8, 2),
    average_score           NUMERIC(5, 2),
    position                INTEGER,
    class_size              INTEGER,
    status                  VARCHAR(20) NOT NULL DEFAULT 'draft',
    class_teacher_remarks   TEXT,
    head_teacher_remarks    TEXT,
    published_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_report_card_summaries_student_period
        UNIQUE (school_id, student_id, academic_year, term),
    CONSTRAINT fk_report_card_summaries_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id),
    CONSTRAINT fk_report_card_summaries_year_school
        FOREIGN KEY (school_id, academic_year_id)
        REFERENCES academic_years(school_id, id),
    CONSTRAINT fk_report_card_summaries_term_school
        FOREIGN KEY (school_id, term_id)
        REFERENCES terms(school_id, id),
    CONSTRAINT fk_report_card_summaries_class_school
        FOREIGN KEY (school_id, class_id)
        REFERENCES classes(school_id, id),
    CONSTRAINT ck_report_card_summaries_status
        CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'published'))
);

CREATE INDEX ix_report_card_summaries_school_id ON report_card_summaries (school_id);
CREATE INDEX ix_report_card_summaries_student_id ON report_card_summaries (student_id);
CREATE UNIQUE INDEX uq_report_card_summaries_school_id_pair
    ON report_card_summaries (school_id, id);

CREATE TABLE report_cards (
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id                 INTEGER NOT NULL,
    school_id                  INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    academic_year              VARCHAR(20) NOT NULL,
    term                       VARCHAR(20) NOT NULL,
    subject                    VARCHAR(100) NOT NULL,
    subject_id                 INTEGER,
    summary_id                 INTEGER,
    score                      NUMERIC(5, 2) NOT NULL,
    grade                      VARCHAR(10) NOT NULL,
    points                     INTEGER,
    teacher_id                 INTEGER,
    teacher_remarks            TEXT,
    class_teacher_remarks      TEXT,
    head_teacher_remarks       TEXT,
    status                     VARCHAR(20) NOT NULL DEFAULT 'submitted',
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_report_cards_student_period_subject
        UNIQUE (student_id, academic_year, term, subject),
    CONSTRAINT fk_report_cards_student_school
        FOREIGN KEY (school_id, student_id)
        REFERENCES students(school_id, id),
    CONSTRAINT fk_report_cards_subject_school
        FOREIGN KEY (school_id, subject_id)
        REFERENCES subjects(school_id, id),
    CONSTRAINT fk_report_cards_summary_school
        FOREIGN KEY (school_id, summary_id)
        REFERENCES report_card_summaries(school_id, id),
    CONSTRAINT fk_report_cards_teacher_school
        FOREIGN KEY (school_id, teacher_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_report_cards_score
        CHECK (score >= 0),
    CONSTRAINT ck_report_cards_status
        CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'published'))
);

CREATE INDEX ix_report_cards_school_id ON report_cards (school_id);
CREATE INDEX ix_report_cards_student_id ON report_cards (student_id);
CREATE INDEX ix_report_cards_subject ON report_cards (subject);
CREATE INDEX ix_report_cards_period ON report_cards (school_id, academic_year, term);
CREATE INDEX ix_report_cards_status ON report_cards (status);
CREATE UNIQUE INDEX uq_report_cards_school_id_pair ON report_cards (school_id, id);

CREATE TABLE report_card_approvals (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    summary_id      INTEGER,
    report_card_id  INTEGER,
    approved_by_id  INTEGER,
    action          VARCHAR(20) NOT NULL,
    comment         TEXT,
    actioned_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_report_card_approvals_summary_school
        FOREIGN KEY (school_id, summary_id)
        REFERENCES report_card_summaries(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_report_card_approvals_report_school
        FOREIGN KEY (school_id, report_card_id)
        REFERENCES report_cards(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_report_card_approvals_user_school
        FOREIGN KEY (school_id, approved_by_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_report_card_approvals_target
        CHECK (summary_id IS NOT NULL OR report_card_id IS NOT NULL),
    CONSTRAINT ck_report_card_approvals_action
        CHECK (action IN ('submitted', 'approved', 'rejected', 'published'))
);

-- ============================================================
-- 9. Notifications
-- ============================================================

CREATE TABLE notification_templates (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER REFERENCES schools(id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    type            VARCHAR(50) NOT NULL,
    channel         VARCHAR(30) NOT NULL DEFAULT 'in_app',
    title           VARCHAR(150),
    message         TEXT NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_notification_templates_school_name
        UNIQUE (school_id, name),
    CONSTRAINT ck_notification_templates_channel
        CHECK (channel IN ('in_app', 'sms', 'email', 'whatsapp'))
);

CREATE TABLE notifications (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    user_id         INTEGER NOT NULL,
    sender_id       INTEGER,
    template_id     INTEGER,
    type            VARCHAR(50) NOT NULL,
    channel         VARCHAR(30) NOT NULL DEFAULT 'in_app',
    title           VARCHAR(150) NOT NULL,
    message         TEXT NOT NULL,
    status          VARCHAR(30) NOT NULL DEFAULT 'queued',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at         TIMESTAMPTZ,
    delivered_at    TIMESTAMPTZ,
    read_at         TIMESTAMPTZ,
    CONSTRAINT fk_notifications_user_school
        FOREIGN KEY (school_id, user_id)
        REFERENCES users(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notifications_sender_school
        FOREIGN KEY (school_id, sender_id)
        REFERENCES users(school_id, id),
    CONSTRAINT fk_notifications_template
        FOREIGN KEY (template_id)
        REFERENCES notification_templates(id),
    CONSTRAINT ck_notifications_channel
        CHECK (channel IN ('in_app', 'sms', 'email', 'whatsapp')),
    CONSTRAINT ck_notifications_status
        CHECK (status IN ('queued', 'sent', 'delivered', 'failed', 'read'))
);

CREATE INDEX ix_notifications_school_id ON notifications (school_id);
CREATE INDEX ix_notifications_user_id ON notifications (user_id);
CREATE INDEX ix_notifications_status ON notifications (status);
CREATE INDEX ix_notifications_type ON notifications (type);

CREATE TABLE notification_preferences (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel         VARCHAR(30) NOT NULL,
    is_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_notification_preferences_user_channel
        UNIQUE (user_id, channel),
    CONSTRAINT ck_notification_preferences_channel
        CHECK (channel IN ('in_app', 'sms', 'email', 'whatsapp'))
);

-- ============================================================
-- 10. Offline Sync
-- ============================================================

CREATE TABLE sync_devices (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    user_id             INTEGER NOT NULL,
    device_id           VARCHAR(255) NOT NULL,
    device_name         VARCHAR(100),
    last_synced_at      TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_sync_devices_user_device
        UNIQUE (user_id, device_id),
    CONSTRAINT fk_sync_devices_user_school
        FOREIGN KEY (school_id, user_id)
        REFERENCES users(school_id, id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_sync_devices_school_id_pair ON sync_devices (school_id, id);

CREATE TABLE sync_changes (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id           INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    user_id             INTEGER NOT NULL,
    device_id           INTEGER,
    entity_type         VARCHAR(80) NOT NULL,
    entity_id           INTEGER,
    action              VARCHAR(50) NOT NULL,
    payload             JSONB NOT NULL,
    idempotency_key     VARCHAR(120) NOT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'received',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    synced_at           TIMESTAMPTZ,
    CONSTRAINT uq_sync_changes_school_key
        UNIQUE (school_id, idempotency_key),
    CONSTRAINT fk_sync_changes_user_school
        FOREIGN KEY (school_id, user_id)
        REFERENCES users(school_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sync_changes_device_school
        FOREIGN KEY (school_id, device_id)
        REFERENCES sync_devices(school_id, id),
    CONSTRAINT ck_sync_changes_action
        CHECK (action IN ('create', 'update', 'delete', 'upsert')),
    CONSTRAINT ck_sync_changes_status
        CHECK (status IN ('received', 'applied', 'rejected', 'conflict'))
);

CREATE INDEX ix_sync_changes_school_id ON sync_changes (school_id);
CREATE INDEX ix_sync_changes_user_id ON sync_changes (user_id);
CREATE INDEX ix_sync_changes_entity ON sync_changes (entity_type, entity_id);
CREATE INDEX ix_sync_changes_status ON sync_changes (status);

CREATE TABLE idempotency_keys (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    key             VARCHAR(255) NOT NULL,
    context         VARCHAR(100),
    response_body   JSONB,
    resolved_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ,
    CONSTRAINT uq_idempotency_keys_school_key
        UNIQUE (school_id, key)
);

-- ============================================================
-- 11. Audit and Exports
-- ============================================================

CREATE TABLE audit_logs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER REFERENCES schools(id) ON DELETE SET NULL,
    actor_user_id   INTEGER REFERENCES users(id) ON DELETE SET NULL,
    actor_role_id   INTEGER REFERENCES roles(id) ON DELETE SET NULL,
    action          VARCHAR(100) NOT NULL,
    entity_type     VARCHAR(100) NOT NULL,
    entity_id       INTEGER,
    before_data     JSONB,
    after_data      JSONB,
    ip_address      VARCHAR(80),
    user_agent      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_logs_school_id ON audit_logs (school_id);
CREATE INDEX ix_audit_logs_actor_user_id ON audit_logs (actor_user_id);
CREATE INDEX ix_audit_logs_action ON audit_logs (action);
CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);

CREATE TABLE data_exports (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    requested_by_id INTEGER,
    export_type     VARCHAR(100) NOT NULL,
    file_url        TEXT,
    status          VARCHAR(30) NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    CONSTRAINT fk_data_exports_requested_by_school
        FOREIGN KEY (school_id, requested_by_id)
        REFERENCES users(school_id, id),
    CONSTRAINT ck_data_exports_status
        CHECK (status IN ('pending', 'processing', 'ready', 'failed', 'expired'))
);

CREATE INDEX ix_data_exports_school_id ON data_exports (school_id);
CREATE INDEX ix_data_exports_status ON data_exports (status);

-- ============================================================
-- 12. updated_at triggers
-- ============================================================

CREATE TRIGGER trg_schools_updated_at
BEFORE UPDATE ON schools
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_school_settings_updated_at
BEFORE UPDATE ON school_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_school_branding_updated_at
BEFORE UPDATE ON school_branding
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_school_subscriptions_updated_at
BEFORE UPDATE ON school_subscriptions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_staff_profiles_updated_at
BEFORE UPDATE ON staff_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_teacher_profiles_updated_at
BEFORE UPDATE ON teacher_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_parent_profiles_updated_at
BEFORE UPDATE ON parent_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_academic_years_updated_at
BEFORE UPDATE ON academic_years
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_terms_updated_at
BEFORE UPDATE ON terms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_classes_updated_at
BEFORE UPDATE ON classes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_streams_updated_at
BEFORE UPDATE ON streams
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_subjects_updated_at
BEFORE UPDATE ON subjects
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_student_enrollments_updated_at
BEFORE UPDATE ON student_enrollments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_fee_categories_updated_at
BEFORE UPDATE ON fee_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_fee_structures_updated_at
BEFORE UPDATE ON fee_structures
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_invoices_updated_at
BEFORE UPDATE ON invoices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_attendance_sessions_updated_at
BEFORE UPDATE ON attendance_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_attendance_updated_at
BEFORE UPDATE ON attendance
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_assessment_types_updated_at
BEFORE UPDATE ON assessment_types
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_assessments_updated_at
BEFORE UPDATE ON assessments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_marks_updated_at
BEFORE UPDATE ON marks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_report_card_summaries_updated_at
BEFORE UPDATE ON report_card_summaries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_report_cards_updated_at
BEFORE UPDATE ON report_cards
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_notification_templates_updated_at
BEFORE UPDATE ON notification_templates
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_notification_preferences_updated_at
BEFORE UPDATE ON notification_preferences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sync_devices_updated_at
BEFORE UPDATE ON sync_devices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 13. Seed data
-- ============================================================

INSERT INTO roles (id, name, description, is_system_role) VALUES
    (1, 'super_admin', 'Platform owner with access to onboarding and tenant management.', TRUE),
    (2, 'admin', 'School administrator with full access inside one school.', TRUE),
    (3, 'teacher', 'Teacher who manages attendance and academic submissions.', TRUE),
    (4, 'parent', 'Guardian who views linked children and makes fee payments.', TRUE),
    (5, 'student', 'Student account with access to own records.', TRUE)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_system_role = EXCLUDED.is_system_role;

INSERT INTO permissions (code, description) VALUES
    ('schools.manage', 'Create and manage schools'),
    ('users.manage', 'Create and manage users'),
    ('students.view', 'View student records'),
    ('students.manage', 'Create and edit student records'),
    ('fees.view', 'View fee records'),
    ('fees.manage', 'Create invoices and record payments'),
    ('attendance.view', 'View attendance records'),
    ('attendance.submit', 'Submit attendance records'),
    ('attendance.correct', 'Correct submitted attendance'),
    ('marks.enter', 'Enter assessment marks'),
    ('report_cards.view', 'View report cards'),
    ('report_cards.submit', 'Submit report cards'),
    ('report_cards.approve', 'Approve report cards'),
    ('report_cards.publish', 'Publish report cards'),
    ('notifications.view', 'View notifications'),
    ('notifications.send', 'Send notifications'),
    ('audit.view', 'View audit logs'),
    ('sync.use', 'Use offline sync endpoints')
ON CONFLICT (code) DO UPDATE SET
    description = EXCLUDED.description;

INSERT INTO role_permissions (role_id, permission_id)
SELECT 1, id FROM permissions
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT 2, id FROM permissions
WHERE code IN (
    'users.manage',
    'students.view',
    'students.manage',
    'fees.view',
    'fees.manage',
    'attendance.view',
    'attendance.submit',
    'attendance.correct',
    'marks.enter',
    'report_cards.view',
    'report_cards.submit',
    'report_cards.approve',
    'report_cards.publish',
    'notifications.view',
    'notifications.send',
    'audit.view',
    'sync.use'
)
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT 3, id FROM permissions
WHERE code IN (
    'students.view',
    'attendance.view',
    'attendance.submit',
    'marks.enter',
    'report_cards.view',
    'report_cards.submit',
    'notifications.view',
    'notifications.send',
    'sync.use'
)
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT 4, id FROM permissions
WHERE code IN ('students.view', 'fees.view', 'attendance.view', 'report_cards.view', 'notifications.view')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT 5, id FROM permissions
WHERE code IN ('students.view', 'fees.view', 'attendance.view', 'report_cards.view', 'notifications.view')
ON CONFLICT DO NOTHING;

-- ============================================================
-- END OF REFINED SCHEMA
-- ============================================================
