import io
import logging
from datetime import datetime

from weasyprint import HTML

logger = logging.getLogger(__name__)


def generate_receipt_pdf(
    school,
    payment,
    receipt,
    student,
    invoice,
) -> bytes:
    from jinja2 import Template

    template_html = """<!DOCTYPE html>
<html><head><style>
@page { size: A4; margin: 25mm 20mm; }
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12px; color: #1a1a1a; }
.header { text-align: center; border-bottom: 3px solid #1a5276; padding-bottom: 10px; margin-bottom: 20px; }
.school-name { font-size: 20px; font-weight: 700; color: #1a5276; text-transform: uppercase; }
.school-contact { font-size: 9px; color: #666; margin-top: 4px; }
.receipt-title { text-align: center; font-size: 16px; font-weight: 700; color: #1a5276; margin: 16px 0; text-decoration: underline; }
.receipt-no { text-align: center; font-size: 11px; color: #555; margin-bottom: 16px; }
.details { margin-bottom: 20px; }
.detail-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px dotted #ccc; }
.detail-label { font-weight: 600; color: #333; }
.detail-value { color: #555; }
.amount-box { background: #f0f7ff; border: 2px solid #1a5276; border-radius: 6px; padding: 16px; text-align: center; margin: 20px 0; }
.amount-label { font-size: 11px; color: #555; text-transform: uppercase; }
.amount-value { font-size: 28px; font-weight: 700; color: #1a5276; margin-top: 4px; }
.footer { text-align: center; margin-top: 30px; padding-top: 10px; border-top: 2px solid #1a5276; font-size: 9px; color: #888; }
.thankyou { text-align: center; font-size: 13px; color: #27ae60; font-weight: 600; margin-top: 12px; }
</style></head><body>
<div class="header">
  <div class="school-name">{{ school_name }}</div>
  <div class="school-contact">{{ school_address }}{% if school_phone %} | Tel: {{ school_phone }}{% endif %}</div>
</div>
<div class="receipt-title">PAYMENT RECEIPT</div>
<div class="receipt-no">Receipt No: {{ receipt_number }}</div>
<div class="details">
  <div class="detail-row"><span class="detail-label">Date:</span><span class="detail-value">{{ issued_date }}</span></div>
  <div class="detail-row"><span class="detail-label">Student:</span><span class="detail-value">{{ student_name }}</span></div>
  <div class="detail-row"><span class="detail-label">Class:</span><span class="detail-value">{{ class_name }}</span></div>
  <div class="detail-row"><span class="detail-label">Admission No:</span><span class="detail-value">{{ admission_number }}</span></div>
  <div class="detail-row"><span class="detail-label">Description:</span><span class="detail-value">{{ description }}</span></div>
  <div class="detail-row"><span class="detail-label">Payment Method:</span><span class="detail-value">{{ payment_method }}</span></div>
  <div class="detail-row"><span class="detail-label">Reference:</span><span class="detail-value">{{ reference }}</span></div>
</div>
<div class="amount-box">
  <div class="amount-label">Amount Paid</div>
  <div class="amount-value">{{ currency }} {{ amount }}</div>
</div>
<div class="thankyou">Thank you for your payment!</div>
<div class="footer">Generated by {{ school_name }} School Management System | {{ generated_date }}</div>
</body></html>"""

    tmpl = Template(template_html)
    html_content = tmpl.render(
        school_name=school.name,
        school_address=school.address or "",
        school_phone=school.phone or "",
        receipt_number=receipt.receipt_number,
        issued_date=receipt.issued_at.strftime("%d %B %Y") if receipt.issued_at else "",
        student_name=student.name if student else "N/A",
        class_name=student.class_name if student else "N/A",
        admission_number=student.admission_number if student else "N/A",
        description=invoice.description or "School Fees Payment" if invoice else "School Fees Payment",
        payment_method=payment.method,
        reference=payment.reference or "N/A",
        currency=school.currency_code,
        amount=f"{payment.amount:,.2f}",
        generated_date=datetime.now().strftime("%d %B %Y"),
    )

    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes
